# Generated by Django 5.2.7 on 2025-10-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='invalidate',
            field=models.BooleanField(default=False),
        ),
    ]
