# Generated by Django 5.2.7 on 2025-10-07 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_otp_invalidate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
