# Generated by Django 5.2.7 on 2025-10-06 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ETLNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchemaNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ETLTableRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.etlnames')),
            ],
        ),
        migrations.CreateModel(
            name='TableNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('etls', models.ManyToManyField(through='api.ETLTableRel', to='api.etlnames')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.schemanames')),
            ],
            options={
                'unique_together': {('name', 'schema')},
            },
        ),
        migrations.AddField(
            model_name='etltablerel',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tablenames'),
        ),
        migrations.AlterUniqueTogether(
            name='etltablerel',
            unique_together={('etl', 'table')},
        ),
    ]
