# Generated by Django 5.2.7 on 2025-10-07 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablenames',
            name='etls',
            field=models.ManyToManyField(related_name='tables', through='api.ETLTableRel', to='api.etlnames'),
        ),
        migrations.AlterField(
            model_name='tablenames',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='api.schemanames'),
        ),
    ]
